import argparse
parser = argparse.ArgumentParser()
parser.add_argument("data_dir", help="data directory of the training files", type=str)
parser.add_argument("--save_dir", help="directory to save the training checkpoint", type=str)
parser.add_argument("--arch", help="model archictecture, ie. 'vgg13'", type=str)
parser.add_argument("--learning_rate", help="learning rate", type=float)
parser.add_argument("--hidden_units", help="hidden units in list form", type=list)
parser.add_argument("--epochs", help="number of epochs to train", type=int)
parser.add_argument("--gpu", help="enable gpu for training", action="store_true")
args = parser.parse_args()
print('Training in Progress.....')
print('Epoch: __ Training Loss: __ Validation Loss: __ Validation Accuracy: __')
print('Training Complete')
print('Check point saved in {}'.format(args.save_dir))